from __future__ import annotations

import base64
import os
import shutil
import sys
from collections.abc import Mapping
from pathlib import Path


CONFIG_FILENAME = "aiworkmonitor.env"
EXECUTABLE_NAME = "AIWorkMonitorAgent.exe"
STARTUP_VALUE_NAME = "AIWorkMonitorAgent"
STARTUP_REGISTRY_PATH = r"Software\Microsoft\Windows\CurrentVersion\Run"


def executable_directory() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent
    return Path.cwd()


def default_install_directory() -> Path:
    local_app_data = os.getenv("LOCALAPPDATA")
    if local_app_data:
        return Path(local_app_data) / "Programs" / "AIWorkMonitor"
    return Path.home() / "AIWorkMonitor"


def _protect_secret(value: str) -> str | None:
    if os.name != "nt":
        return None
    try:
        import win32crypt

        encrypted = win32crypt.CryptProtectData(
            value.encode("utf-8"),
            "AIWorkMonitor token",
            None,
            None,
            None,
            0,
        )
        return base64.b64encode(encrypted).decode("ascii")
    except Exception:
        return None


def _unprotect_secret(value: str) -> str:
    if os.name != "nt":
        raise ValueError("DPAPI-protected configuration can only be read on Windows")
    try:
        import win32crypt

        encrypted = base64.b64decode(value, validate=True)
        _, decrypted = win32crypt.CryptUnprotectData(encrypted, None, None, None, 0)
        return decrypted.decode("utf-8")
    except Exception as exc:
        raise ValueError("Unable to decrypt the saved access token for this Windows account") from exc


def read_config_values(path: Path, *, required: bool = False) -> dict[str, str]:
    if not path.is_file():
        if required:
            raise FileNotFoundError(f"Config file does not exist: {path}")
        return {}

    values: dict[str, str] = {}
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            raise ValueError(f"Invalid config line {line_number}: expected KEY=VALUE")
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if not key.startswith("AIWM_"):
            raise ValueError(f"Invalid config line {line_number}: unsupported key {key!r}")
        if key == "AIWM_TOKEN_DPAPI":
            values["AIWM_TOKEN"] = _unprotect_secret(value)
        else:
            values[key] = value

    workdir = values.get("AIWM_CLAUDE_WORKDIR")
    if workdir and not Path(workdir).is_absolute():
        values["AIWM_CLAUDE_WORKDIR"] = str((path.parent / workdir).resolve())
    return values


def load_config_file(path: Path, *, required: bool = False) -> bool:
    values = read_config_values(path, required=required)
    if not values and not path.is_file():
        return False
    for key, value in values.items():
        os.environ.setdefault(key, value)
    return True


def write_agent_config(path: Path, values: Mapping[str, str | bool | float]) -> None:
    token = str(values.get("AIWM_TOKEN", ""))
    protected_token = _protect_secret(token) if token else None
    lines = [
        "# Generated by AIWorkMonitor Windows GUI.",
        "# The access token is protected with Windows DPAPI when available.",
    ]
    if protected_token:
        lines.append(f"AIWM_TOKEN_DPAPI={protected_token}")
    else:
        lines.append(f"AIWM_TOKEN={token}")

    ordered_keys = (
        "AIWM_RELAY_URL",
        "AIWM_DEVICE_ID",
        "AIWM_DEVICE_NAME",
        "AIWM_SAMPLE_INTERVAL",
        "AIWM_ALLOW_CLAUDE_COMMANDS",
        "AIWM_CLAUDE_WORKDIR",
        "AIWM_CLAUDE_LOG_GLOB",
        "AIWM_CHATGPT_LOG_GLOB",
    )
    for key in ordered_keys:
        if key not in values:
            continue
        raw_value = values[key]
        if isinstance(raw_value, bool):
            value = "true" if raw_value else "false"
        else:
            value = str(raw_value)
        if "\n" in value or "\r" in value:
            raise ValueError(f"Configuration value {key} cannot contain a new line")
        lines.append(f"{key}={value}")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def startup_command(executable: Path) -> str:
    return f'"{executable.resolve()}" --background'


def get_startup_command() -> str | None:
    if os.name != "nt":
        return None
    import winreg

    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, STARTUP_REGISTRY_PATH) as key:
            value, _ = winreg.QueryValueEx(key, STARTUP_VALUE_NAME)
            return str(value)
    except FileNotFoundError:
        return None


def set_startup(enabled: bool, executable: Path) -> None:
    if os.name != "nt":
        raise OSError("Startup registration is only supported on Windows")
    import winreg

    with winreg.CreateKey(winreg.HKEY_CURRENT_USER, STARTUP_REGISTRY_PATH) as key:
        if enabled:
            winreg.SetValueEx(
                key,
                STARTUP_VALUE_NAME,
                0,
                winreg.REG_SZ,
                startup_command(executable),
            )
        else:
            try:
                winreg.DeleteValue(key, STARTUP_VALUE_NAME)
            except FileNotFoundError:
                pass


def install_application(
    source_executable: Path,
    install_directory: Path,
    config_values: Mapping[str, str | bool | float],
    *,
    start_with_windows: bool,
) -> Path:
    source = source_executable.resolve()
    if not source.is_file() or source.suffix.lower() != ".exe":
        raise ValueError("Installation is available from the packaged EXE only")

    destination_directory = install_directory.expanduser().resolve()
    destination_directory.mkdir(parents=True, exist_ok=True)
    destination = destination_directory / EXECUTABLE_NAME
    if source != destination:
        shutil.copy2(source, destination)
    write_agent_config(destination_directory / CONFIG_FILENAME, config_values)
    set_startup(start_with_windows, destination)
    return destination
